#!/bin/bash

############################################
#      		Base exports
############################################

# Tools
export LOCAL_PATH="/usr/local"
export BASE_PATH="$PATH:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
export BREW_HOME="$LOCAL_PATH/opt"

export ASDF_PATH="$HOME/.asdf/shims"
export ASDF_DATA_DIR="$HOME/.asdf"

export DEVELOPMENT_HOME="$HOME/dev"
export RUBY_HOME="$ASDF_PATH/ruby"
export CONDA_PATH="/usr/local/anaconda3/bin"

export _ZO_DATA_DIR="$HOME" # zoxide database directory

# System configs
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export TERM='xterm-256color'
export EDITOR='nvim'
export SAVEHIST=10000
# export HISTFILE=~/.zsh_history Not needed anymore due to pretzo. New value is ~/.zhistory
export ENHANCD_FILTER=fzy
export CACHE_DIR=${XDG_CACHE_DIR:-$HOME/.cache}

# Go configs
export GOPATH="$DEVELOPMENT_HOME" # go env GOPATH
export GOPATH_BIN="$GOPATH/bin" # For convenience

# Node configs
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # Load NVM

# Python configs
export PYENV_ROOT="$LOCAL_PATH/opt/pyenv" # PYENV_ROOT="$HOME/.pyenv"

##### PATH CONFIG #####
export PATH="$ASDF_PATH:$BASE_PATH:$DEVELOPMENT_HOME:$GOPATH_BIN:$CONDA_PATH:$PYENV_ROOT/bin"
#######################

# Fzf configs
export FZF_DEFAULT_OPTS='--height=50% --min-height=15 --reverse'
export FZF_DEFAULT_COMMAND='rg --files --no-ignore-vcs --hidden'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND" # Paste the selected files and directories onto the command-line
export FZF_ALT_C_COMMAND="fd --type d . $HOME --color=never" # Go into the selected directory (rg doesn't quite support this)
export FZF_COMPLETION_OPTS='+c -x'
export FZF_ALT_C_OPTS='--height=50% --min-height=15 --reverse'
