#!/bin/bash

############################################
#         Source ZGen framework
############################################

# Don't allow compinit to be called by zgenom (already called by pretzo completion)
export ZGEN_AUTOLOAD_COMPINIT=0

# load zgenom
source "${HOME}/.zgenom/zgenom.zsh"

# Check for plugin and zgenom updates every 7 days
# This does not increase the startup time.
zgenom autoupdate

setopt promptsubst

# If the init script doesn't exist
if ! zgenom saved; then
  zgenom prezto

  # Stolen from oh-my-zsh since I don't want to bloat the config
  zgenom load ~/.zsh_plugins/git.plugin.zsh # Git command support with various defined aliases (have to be these aliases, I don't like the ones from other packages)
  zgenom load ~/.zsh_plugins/search_keys.plugin.zsh # Autocompletion with up arrow on the terminal.

  ###################################################################3

  zgenom load djui/alias-tips # Gives a tip when you use a command that as a defined alias.
  # zgenom load b4b4r07/enhancd # cd with fuzzy finding. Dependency: jhawthorn/fzy. Usage: cd
  zgenom load paulirish/git-open # Open github from terminal

  zgenom save

  zgenom compile "$HOME/.zshrc"
fi

# Hack to fix this plugin since zgenom is not executing the init script
# correctly
# source "$HOME/.zgenom/sources/b4b4r07/enhancd/___/init.sh"
