#!/bin/bash

# NOTICE: This is deprecated in favor of zgen

############################################
#         Source Zplug framework
############################################

source $ZPLUG_HOME/init.zsh

zplug "plugins/git", from:oh-my-zsh # Git command support with various defined aliases.
zplug "plugins/z", from:oh-my-zsh # Jump between directories. Usage: z
zplug "plugins/tmuxinator", from:oh-my-zsh # Complex tmux. Dependecy: gem install tmuxinator
zplug "djui/alias-tips", from:github # Gives a tip when you use a command that as a defined alias.
zplug "hchbaw/auto-fu.zsh", from:github # Gives information about command flags, auto-complete style.
zplug "b4b4r07/enhancd", use:init.sh, from:github # cd with fuzzy finding. Dependecy: jhawthorn/fzy. Usage: cd
zplug "robbyrussell/oh-my-zsh", use:"lib/*" # adds support for oh-my-zsh. Note, this adds support for the libs, not the plugins.
zplug "plugins/bundler", from:oh-my-zsh # Bundler support and a bunch of other aliases for Ruby dev.
zplug "paulirish/git-open", as:plugin # Open github from terminal
# Load async lib
zplug "mafredri/zsh-async", from:github

# Load the theme.
zplug sindresorhus/pure, use:pure.zsh, from:github, as:theme
