#!/bin/bash

# NOTICE: This is deprecated in favor of zgen

############################################
#         Source ZPlugins framework
############################################

source "$HOME/.zplugin/bin/zplugin.zsh"

# Git command support with various defined aliases.
zplugin ice svn wait"0" silent src"git-completion.bash" ; zplugin snippet OMZ::plugins/gitfast
zplugin ice svn wait"0" silent ; zplugin snippet OMZ::plugins/git/git.plugin.zsh

# Jump between directories. Usage: z
zplugin ice svn wait"0" silent ; zplugin snippet OMZ::plugins/z

# Gives a tip when you use a command that as a defined alias.
zplugin ice wait"0" silent; zplugin light djui/alias-tips

# cd with fuzzy finding. Dependecy: jhawthorn/fzy. Usage: cd
zplugin ice wait"0" silent ; zplugin light b4b4r07/enhancd

# OMZ supported libs
omz_libs=(
bzr.zsh
clipboard.zsh
compfix.zsh
completion.zsh
correction.zsh
diagnostics.zsh
directories.zsh
functions.zsh
git.zsh
grep.zsh
history.zsh
key-bindings.zsh
misc.zsh
# nvm.zsh
prompt_info_functions.zsh
spectrum.zsh
termsupport.zsh
theme-and-appearance.zsh
)

# Support for oh-my-zsh. Note, this adds support for the libs, not the plugins.
zplugin ice svn multisrc"\${omz_libs[@]}" pick"" wait"0" silent ; zplugin snippet OMZ::lib

# Open github from terminal
zplugin ice wait"0" silent ; zplugin light paulirish/git-open

# Theme with async lib
zplugin ice pick"async.zsh" src"pure.zsh"; zplugin light sindresorhus/pure

# Syntax highlighting that calls compinit at startup
zplugin ice atinit'zpcompinit' ; zplugin light zdharma/fast-syntax-highlighting
