#!/bin/bash

# Custom command: fe
# Open the selected file with the default editor -fe [FUZZY PATTERN]
#   - Bypass fuzzy finder if there's only one match (--select-1)
#   - Exit if there's no match (--exit-0)
# From: https://github.com/junegunn/fzf/wiki/Examples#opening-files
fe() {
  local files
  IFS=$'\n' files=($(fzf-tmux --query="$1" --multi --select-1 --exit-0))
  [[ -n "$files" ]] && ${EDITOR:-vim} "${files[@]}"
}
