#!/bin/bash

# Custom command: fif
# Find in file using ripgrep combined with preview
# find-in-file - usage: fif <searchTerm>
# From: https://github.com/junegunn/fzf/wiki/Examples#searching-file-contents
fif() {
    if [ ! "$#" -ge 1 ]; then echo "Need a string to search for!"; return 1; fi
    rg --files-with-matches --hidden --no-messages $1 | fzf --preview "highlight -O ansi -l {} 2> /dev/null | rg --colors 'match:bg:yellow' --ignore-case --hidden --pretty --context 10 $1 || rg --ignore-case --hidden --pretty --context 10 $1 {}"
}
